pkg config path debug

diff --git a/.github/workflows/windows-continuous.yml b/.github/workflows/windows-continuous.yml
--- a/.github/workflows/windows-continuous.yml
+++ b/.github/workflows/windows-continuous.yml
@@ -61,6 +61,10 @@ jobs:
         run: |
           C:\msys64\usr\bin\bash -lc "source ~/setup-env.sh && git clone https://github.com/bitcoin-core/secp256k1 && cd secp256k1 && git checkout v0.5.1 && ./autogen.sh && ./configure --enable-module-schnorrsig --enable-module-extrakeys --enable-module-ecdh --enable-experimental --enable-module-recovery && make && make install && cd .."
 
+      - name: Debug pkg-config
+        run: |
+          C:\msys64\usr\bin\bash -lc "cd /d/a/futr/futr && source ~/setup-env.sh && echo 'pkg-config --libs lmdb:' && pkg-config --libs lmdb || echo 'Failed to get libs for lmdb' && echo 'pkg-config --libs libsecp256k1:' && pkg-config --libs libsecp256k1 || echo 'Failed to get libs for libsecp256k1' && echo 'pkg-config --cflags lmdb:' && pkg-config --cflags lmdb || echo 'Failed to get cflags for lmdb' && echo 'pkg-config --cflags libsecp256k1:' && pkg-config --cflags libsecp256k1 || echo 'Failed to get cflags for libsecp256k1' && echo ''"
+
       - name: Build with Cabal
         run: |
           C:\msys64\usr\bin\bash -lc "cd /d/a/futr/futr && source ~/setup-env.sh && cabal build --project-file=cabal.project.windows"
